// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhbGod7e6PIOBhHuZJb6wk0TFg-LvIg-U',
    appId: '1:619000166635:web:6dc3af959cef9fb62ae6ae',
    messagingSenderId: '619000166635',
    projectId: 'i-contacts-app',
    authDomain: 'i-contacts-app.firebaseapp.com',
    storageBucket: 'i-contacts-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiuBcD5KAlbXt-WO2RTpFCYeiW9fpxwWA',
    appId: '1:619000166635:android:8f6e38b9a7de59032ae6ae',
    messagingSenderId: '619000166635',
    projectId: 'i-contacts-app',
    storageBucket: 'i-contacts-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0SZAbTjbt1JUMDrzVYtD2LxJuKlNQEk',
    appId: '1:619000166635:ios:75b9c20b177858eb2ae6ae',
    messagingSenderId: '619000166635',
    projectId: 'i-contacts-app',
    storageBucket: 'i-contacts-app.appspot.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0SZAbTjbt1JUMDrzVYtD2LxJuKlNQEk',
    appId: '1:619000166635:ios:3ff1c36a5c4713d52ae6ae',
    messagingSenderId: '619000166635',
    projectId: 'i-contacts-app',
    storageBucket: 'i-contacts-app.appspot.com',
    iosBundleId: 'com.example.contacts.RunnerTests',
  );
}
